language: node_js
node_js:
  - 8

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
  - yarn
#  - ./node_modules/.bin/grunt build

script:
  - ./node_modules/.bin/jest --coverage

after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)
