name: 'CI: µ'

on: [push]

jobs:
  lint-changelog:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1
        with:
          rules: './.github/workflows/lint/rules/changelog.js'
          config: '/lint/config/changelog.yml'
          args: './CHANGELOG.md'

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npm run build --if-present

      - run: npm test
        env:
          CI: true
#
#  publish-npm:
#    needs: build
#    runs-on: ubuntu-latest
#    on:
#      push: release
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 13
#          registry-url: https://registry.npmjs.org/
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
